### ISSUE TITLE
feature: 数据建模

### ISSUE THREAD

**Issue by kenleee1230** [TencentBlueKing/bk-training-award-open#7]
陈亦博
- 秘书表
- 奖项表

杨梦龙
- 申请表
- 历史记录表

**Comment by chenyibo111** [comment]
奖项表
```
class Awards(models.Model):
    award_name = models.CharField(max_length=128, verbose_name="奖项名称")
    award_state = models.CharField(max_length=128, verbose_name="奖项状态")
    award_level = models.CharField(max_length=128, verbose_name="奖项级别")
    award_description = models.CharField(max_length=512, verbose_name="奖项描述")
    award_consultant = models.CharField(max_length=128, verbose_name="奖项顾问")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    update_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")
    start_time = models.DateTimeField(verbose_name="开始时间")
    end_time = models.DateTimeField(verbose_name="截止时间")
```

奖项表
```
class Secretary(models.Model):
    account_id = models.CharField(max_length=128, unique=True, verbose_name="用户账号")
    name = models.CharField(max_length=128, null=True, blank=True, verbose_name="用户姓名")
    phone = models.CharField(max_length=30, null=True, blank=True, verbose_name="电话号码")
    email = models.EmailField(null=True, blank=True, verbose_name="邮箱")
```

**Comment by kenleee1230** [comment]
> 
抱歉没有说明清楚，秘书表指的是[部门和秘书的映射关系表]，即记录 部门id 和 秘书账户id。

**Comment by qqqqqie** [comment]
1. 两个都是奖项表吗?
2. 猜测第二个是秘书表,我们并不需要单独的秘书表,只是要做一个部门和秘书的映射,来记录部门是由哪些秘书管的
3. 每个奖项都是有图片的,看了一下奖项表中没有关于图片的字段,那文件和图片应该如何对应起来?

**Comment by chenyibo111** [comment]
奖项表
class Awards(models.Model):
    award_name = models.CharField(max_length=128, verbose_name="奖项名称")
    award_level = models.CharField(max_length=128, verbose_name="奖项级别")
    award_description = models.CharField(max_length=512, verbose_name="奖项描述")
    award_consultant = models.CharField(max_length=128, verbose_name="奖项顾问")
    award_image = models.ImageField(max_length=1000, upload_to='img')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    update_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")
    start_time = models.DateTimeField(verbose_name="开始时间")
    end_time = models.DateTimeField(verbose_name="截止时间")

秘书表
class Secretary(models.Model):
    user_id = models.CharField(max_length=128, verbose_name="用户id")
    group_id = models.CharField(max_length=128, verbose_name="组id")

**Comment by qqqqqie** [comment]
ImageField这个字段有使用过么，如果是前后端分离这样非模板的用法，拿到的是什么样的数据

**Comment by chenyibo111** [comment]
我用element-ui的upload组件试过，前端上传图片到后端，后端通过request.FILES['file'] 可以得到这个图片对象，可以访问它的name,size等，数据库中保存的是字符串格式的图片名

**Comment by chenyibo111** [comment]
我觉得MagicBox里的upload组件应该也行吧

**Comment by qqqqqie** [comment]
刚刚说错了，原本想问的是如何再传给前端，不过想了一下应该是可以存到静态文件夹里，然后前端通过文件名访问静态资源拿到，看看能不能实现在前端显示

**Comment by qqqqqie** [comment]
不过有一个需要注意的点，就是文件名有可能会重复，需要考虑一下处理成可读并且不重复的

**Comment by YmmLom** [comment]
```
# 申请表
class Apply(models.Model):
    award_id = models.IntegerField(verbose_name="奖项id")
    apply_time = models.DateTimeField(verbose_name="申请时间")
    apply_reason = models.TextField(verbose_name="申请理由")
    apply_id = models.IntegerField(verbose_name="申请人id")
    apply_attachments = models.TextField(null=True, verbose_name="附件")
    is_apply = models.BooleanField(default=False, verbose_name="是否申请")


# 历史记录表
class History(models.Model):
    apply_id = models.IntegerField(verbose_name="申请id")
    approval_id = models.IntegerField(verbose_name="审批人id")
    approval_time = models.DateTimeField(default=timezone.now, verbose_name="审批时间")
    approval_text = models.TextField(verbose_name="审批评语")
    is_approval = models.BooleanField(default=False, verbose_name="是否审批")
```

**Comment by chenyibo111** [comment]
> 不过有一个需要注意的点，就是文件名有可能会重复，需要考虑一下处理成可读并且不重复的

文件名到时候会做处理，这样存储前端能够拿到图片，我试过了

**Comment by kenleee1230** [comment]
> 

历史记录表昨天开会时已提到不需要了。

**Comment by kenleee1230** [comment]
> ```
> # 申请表
> class Apply(models.Model):
>     award_id = models.IntegerField(verbose_name="奖项id")
>     apply_time = models.DateTimeField(verbose_name="申请时间")
>     apply_reason = models.TextField(verbose_name="申请理由")
>     apply_id = models.IntegerField(verbose_name="申请人id")
>     apply_attachments = models.TextField(null=True, verbose_name="附件")
>     is_apply = models.BooleanField(default=False, verbose_name="是否申请")
> 
> 
> # 历史记录表
> class History(models.Model):
>     apply_id = models.IntegerField(verbose_name="申请id")
>     approval_id = models.IntegerField(verbose_name="审批人id")
>     approval_time = models.DateTimeField(default=timezone.now, verbose_name="审批时间")
>     approval_text = models.TextField(verbose_name="审批评语")
>     is_approval = models.BooleanField(default=False, verbose_name="是否审批")
> ```

申请表
【类命名】应为名词而非动词，例如，AwardApplicationRecord
【字段命名】apply是动词，应为application
【附件】字段用了TextField，请问多个文件访问路径保存的思路是？
【申请人id】用了intField，请问如果一条申请记录里有多个申请人怎么办？（比如有个团队奖，申请的话需要把团队成员都选上）
【是否申请】申请的状态包含了`草稿`，`评审中`，`不通过`，其中基于[草稿]和[不通过]两种状态有相应的操作[编辑申请/发起申请]、[重新申请]，如果只是布尔类型应该不太好搞，可以看下ChoiceField

**Comment by YmmLom** [comment]
```
from django.db import models
from django_jsonfield_backport import models as json_models
# 申请表
class AwardApplicationRecord(models.Model):
    award_id = models.IntegerField(verbose_name="奖项id")
    application_time = models.DateTimeField(verbose_name="申请时间")
    application_reason = models.TextField(verbose_name="申请理由")
    application_id = json_models.JSONField(verbose_name="申请人id列表")
    # 附件地址列表
    application_attachments = json_models.JSONField(verbose_name="申请附件地址列表")
    APPROVAL_STATE = [
        (0, "待审批"),
        (1, "审批通过"),
        (2, "审批不通过"),
        (3, "草稿"),
    ]
    approval_state = models.IntegerField(choices=APPROVAL_STATE, default=3, verbose_name="审批状态")
    approval_id = models.IntegerField(verbose_name="审批人id", null=True)
    approval_time = models.DateTimeField(verbose_name="审批时间", null=True)
    approval_text = models.TextField(verbose_name="审批评语", null=True)
```
附件想的是存储文件信息列表，列表中项为dict,包含文件地址，大小等信息

**Comment by kenleee1230** [comment]
> 

奖项表
1.需要增加一个[结束时间]的字段，用来判断该奖项的评审是否结束
2.【开始时间】-->【开始申请时间】；【截止时间】-->【截止申请时间】
